### ISSUE TITLE
Emotes cause auto-scroll to stop

### ISSUE THREAD

**Issue by laagone** [Jiiks/twitchcord#4]
When someone uses an emote, the message feed doesn't auto-scroll anymore if new messages come in. It looks like the page scrolls up slightly because of the emote dimensions, which causes it to pause until you scroll back down. Also, when switching between channels, the page is scrolled up a bit most likely due to the emotes so you have to manually scroll down again to see the most recent messages.

I'm aware this plugin is included in BetterDiscordApp now, not sure if it's going to be deprecated because of it, but regardless I've also heard the same issue happens on BDA. I would leave this at BDA's issues page but I feel it's more appropriate here since I couldn't manage to get the installation for it working and thus couldn't use it myself.

**Comment by Jiiks** [comment]
https://github.com/Jiiks/BetterDiscordApp
